### ISSUE TITLE
Adding "userprofile" from API unauthenticated

### ISSUE THREAD

**Issue by thomasrosnet** [IFB-ElixirFr/ifbcat#100]
It is currently possible to add userprofile via the API form while not being connected, i don't think this is entended.

**Comment by joncison** [comment]
Indeed, it's not intended.

The valid ways to create new UserProfile objects:
1. Superuser (by Django admin interface)
2. Anyone who uses /login endpoint (to create an account)

**Comment by bryan-brancotte** [comment]
Hi @joncison 

I am not sure to understand the seconde condition, you wrote "Anyone who uses /login endpoint", you mean /api/login ? I just discovered and tested it so I might be wrong, but it only allows to create token, not account. Do you mean that an admin get a token, send it to a user which then use it to create an account in /api/userprofile/ ?

Another solution could be to let the creation of UserProfile open, but create account that are not active. Admin would then have to set is_valid to True in the admin UI.

Cheers,

**Comment by joncison** [comment]
Apologies, I was a bit hasty / confusing in my post.  There's a design decision to make (so cc @hmenager) but I'm assuming that in the first instance we don't want anyone to be able to create user accounts (rather have superuser do this upon request), but then later (when we expect more users) to open this up so that the burden of account creation is shifted from superuser to users.  

So we might (sooner or later) be better with a api/registration endpoint, and then perhaps refactor api/userprofile to api/person ?

What do you think @hmenager @bryan-brancotte @thomasrosnet ?

**Comment by bryan-brancotte** [comment]
user cannot be created when not logged in anymore. For now only authenticated user can create user
