### ISSUE TITLE
Date and time-picker widgets in browsable UI

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#16]
See https://github.com/joncison/ifbcat-sandbox/issues/15

For Event model, would be very nice to have date and time picker widgets in the broswable API UI for the ``dates`` field, such as those provided by the DJango admin interface. 

This in turn means overcoming the "Lists are not currently supported in HTML input" issue I'm having for the ``dates`` field in the browsable UI:
![image](https://user-images.githubusercontent.com/1506863/87985914-4fdd4480-cad4-11ea-9d26-897ead298a37.png)

**Comment by bryan-brancotte** [comment]
Hi Jon

This would be nice but after some search with "Lists are not currently supported in HTML input." it seems that we are not the only one who would want it, but still do not have it.

Note also that I had to make dates optional in the serializer with 4a12b83cc80ccb6c43f2481a792f27bdadc77dd4 in order to still be able to update an event with the browsable API

**Comment by joncison** [comment]
Indeed.  I propose we just keep this issue open until a solution presents itself.  Thanks for the fix making dates optional.

cc @hmenager - I think we can make the Django browsable API a "good enough" front-end for the catalogue - at least in the 1st instance when it's mostly friends using it.  But there are limitations (see above).

**Comment by joncison** [comment]
@bryan-brancotte, in a previous commit, I'd set dates to be mandatory (I'd forgotten about this issue).  So that may need to be reverted back to optional.  Let's leave it open until we think a bit more about it.  cc @hmenager
