### ISSUE TITLE
Should event always have a start_date

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#184]
Hi @hchiapello 

We have an event (https://catalogue.france-bioinformatique.fr/api/event/427/) without date as pointed by @Sylmila . I think your are its author. Is it intended to not have a start_date and the possibility kept ? or should start_date be mandatory for event ?

**Comment by bryan-brancotte** [comment]
Hi @hchiapello.
If the date is intentionally missing, we can have instead a boolean "draft" indicating that the event should not be published, and where the date is allowed to not be set. (When draft is false, date_start is mandatory)

**Comment by olisand** [comment]
Hello @bryan-brancotte 
I don't know if Helene created that event, but I agree that an event should haver a date_start. A draft tag is not a bad idea if someone wants to add an event for which the date_start is not decided yet. But I am not sure this is really necessary since adding the event could wait until the date_start is decided.

**Comment by bryan-brancotte** [comment]
Hi @Aziguy 

The draft boolean is a go, we should require start_date only when the event is not a draft. 
If you think that other attributs could become conditionally required, please suggest them.

Thanks

**Comment by Aziguy** [comment]
We should close this issue @bryan-brancotte

**Comment by bryan-brancotte** [comment]
Yes, closed via #193
